name: another github action
on:
  push:
    branches: [ main ]
    paths:
    - .github/workflows/another-action.yml
    - version.txt
  pull_request:
    branches: [ main ]
    paths:
    - .github/workflows/another-action.yml
    - version.txt
  release:
    types:
      - published
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sleep 120s