name: Cancel Previous Workflows
on:
  workflow_run:
    workflows: ["some-action.yml, another-action.yml"]
    branches: [main]
    types:
      - requested
jobs:
  cancel:
    if: (github.event_name != 'release') && (github.event_name != 'push') 
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: "some-action.yml, another-action.yml"