name: Cancel 2
on:
  workflow_run:
    workflows: ["some action", "another action"]
    types:
      - requested
  pull_request:
    branches: [ main ]
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}