name: Cancel Previous Workflows
on:
  workflow_run:
    branches: [ main ]
    workflows: ["some github action", "another github action"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}