name: Cancel Previous Workflows
on:
  pull_request:
    branches: [ main ]
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: "some-action.yml"