name: another action
on:
  push:
    branches: [ main ]
    paths:
    - .github/workflows/untriggered-action.yml
  pull_request:
    branches: [ main ]
    paths:
    - .github/workflows/untriggered-action.yml
  release:
    types:
      - published
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sleep 120s